services:
  wud:
    image: fmartinou/whats-up-docker
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - WUD_TRIGGER_HTTP_NTFY_URL=${NTFY_URL}/${NTFY_TOPIC}?auth=${NTFY_TOKEN}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - frontend
      - wud-net

  docknify:
    image: docker:cli
    container_name: docknify
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NTFY_URL=${NTFY_URL}
      - NTFY_TOPIC=${NTFY_TOPIC}
      - NTFY_TOKEN=${NTFY_TOKEN}
    command: >
      sh -c "apk add --no-cache curl jq && docker events --filter 'type=container' --filter 'event=die' --filter 'event=kill' --format '{{json .}}' | while read event; do name=$$(echo $$event | jq -r '.Actor.Attributes.name'); curl -H 'Authorization: Bearer $$NTFY_TOKEN' -H 'X-Title: Container Stopped' -H 'Tags: warning,tractor' -d \"Container $$name was stopped or killed!\" $$NTFY_URL/$$NTFY_TOPIC; done"

networks:
  frontend:
    external: true
  wud-net:
    name: wud-net
    driver: bridge
