services:
  wud:
    image: fmartinou/whats-up-docker
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - WUD_TRIGGER_NTFY_MYALERT_URL=${NTFY_URL}
      - WUD_TRIGGER_NTFY_MYALERT_TOPIC=${NTFY_TOPIC}
      - WUD_TRIGGER_NTFY_MYALERT_AUTH_TOKEN=${NTFY_TOKEN}
      - WUD_TRIGGER_NTFY_MYALERT_TITLE="WUD"
      - WUD_TRIGGER_NTFY_MYALERT_MESSAGE="Container {{app}} updated to {{version}}"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - frontend
      - wud-net

networks:
  frontend:
    external: true
  wud-net:
    name: wud-net
    driver: bridge
